# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build --if-present

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Create SSH config
      run: |
        mkdir -p ~/.ssh
        cat <<EOF > ~/.ssh/config
        Host ssh.leandre.xyz
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
    
        Host 192.168.1.104
            ProxyJump gateway@ssh.leandre.xyz
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
        EOF
        chmod 600 ~/.ssh/config

    - name: Deploy via SCP with ProxyJump
      run: |
        scp \
          -o "ProxyJump gateway@${{ secrets.JUMP_HOST }}" \
          -i ~/.ssh/id_rsa -r ./build \
          vsc@${{ secrets.SERVER_HOST }}:/home/vsc/next-app-build
